// Auto-generated from "Order & Execution Object Mapping, Business Criteria & Business Classification.xlsx" on 2025-12-25T13:54:51.857Z
// Column B = Field Name, Column F = Field Type (mapped to Identifier/Business Classification/Economics)

const orderFields = {
  Order_ID: "Identifier",
  Order_ID_Version: "Identifier",
  Order_ID_Session: "Identifier",
  Order_ID_Instance: "Identifier",
  Parent_Order_ID: "Identifier",
  Cancelreplace_Order_ID: "Identifier",
  Linked_Order_ID: "Identifier",
  Linked_Order_Type: "Business Classification",
  Order_Action: "Business Classification",
  Order_Status: "Business Classification",
  Order_Capacity: "Business Classification",
  Order_Destination: "Economics",
  Order_Client_Ref: "Business Classification",
  Order_Client_Ref_Details: "Business Classification",
  Order_Executing_Entity: "Business Classification",
  Order_Booking_Entity: "Business Classification",
  Order_Position_Account: "Identifier",
  Order_Side: "Economics",
  Order_Client_Capacity: "Business Classification",
  Order_Manual_Indicator: "Business Classification",
  Order_Request_Time: "Economics",
  Order_Event_Time: "Economics",
  Order_Manual_Timestamp: "Economics",
  Order_OMS_Source: "Identifier",
  Order_Publishing_Time: "Economics",
  Order_Trade_Date: "Economics",
  Order_Quantity: "Economics",
  Order_Price: "Economics",
  Order_Type: "Economics",
  Order_TimeInforce: "Economics",
  Order_Execution_Instructions: "Economics",
  Order_Attributes: "Economics",
  Order_Restrictions: "Business Classification",
  Order_Auction_Indicator: "Economics",
  Order_Swap_Indicator: "Business Classification",
  Order_OSI: "Economics",
  Order_Instrument_ID: "Identifier",
  Order_Linked_Instrument_ID: "Identifier",
  Order_Currency_ID: "Identifier",
  Order_Flow_Type: "Business Classification",
  Order_Algo_Instruction: "Economics",
  Order_Symbol: "Economics",
  Order_Instrument_Reference: "Identifier",
  Order_Instrument_Reference_Value: "Identifier",
  Order_Option_Put_Call: "Economics",
  Order_Option_Strike_Price: "Economics",
  Order_Option_Leg_Indicator: "Economics",
  Order_Compliance_ID: "Identifier",
  Order_Entity_ID: "Identifier",
  Order_Executing_Account: "Identifier",
  Order_Clearing_Account: "Identifier",
  Order_Client_Order_ID: "Economics", 
  Order_Routed_Order_ID: "Economics",
  Order_Trading_Owner: "Business Classification",
  Order_Extended_Attribute: "Business Classification",
  Order_Quote_ID: "Identifier",
  Order_Represent_Order_ID: "Identifier",
  Order_On_Behalf_Comp_ID: "Identifier",
  Order_Spread: "Economics",
  Order_Amend_Reason: "Business Classification",
  Order_Cancel_Reject_Reason: "Business Classification",
  Order_Bid_Size: "Economics",
  Order_Bid_Price: "Economics",
  Order_Ask_Size: "Economics",
  Order_Ask_Price: "Economics",
  Order_Basket_ID: "Identifier",
  Order_Cum_Qty: "Economics",
  Order_Leaves_Qty: "Economics",
  Order_Stop_Price: "Economics",
  Order_Discretion_Price: "Economics",
  Order_Exdestination_Instruction: "Economics",
  Order_Execution_Parameter: "Economics",
  Order_Infobarrier_ID: "Business Classification",
  Order_Leg_Ratio: "Economics",
  Order_Locate_ID: "Identifier",
  Order_Negotiated_Indicator: "Business Classification",
  Order_Open_Close: "Economics",
  Order_Participant_Priority_Code: "Economics",
  Order_Action_Initiated: "Business Classification",
  Order_Package_Indicator: "Business Classification",
  Order_Package_ID: "Identifier",
  Order_Package_Pricetype: "Business Classification",
  Order_Strategy_Type: "Business Classification",
  Order_Secondary_Offering: "Business Classification",
  Order_Start_Time: "Economics",
  Order_TIF_Expiration: "Economics",
  Order_Parent_Child_type: "Business Classification",
  Order_Minimum_Qty: "Economics",
  Order_Trading_Session: "Business Classification",
  Order_Display_Price: "Economics",
  Order_Seq_Number: "Identifier",
  ATS_Display_Indicator: "Business Classification",
  Order_Display_Qty: "Economics",
  Order_Working_Price: "Economics",
  ATS_Order_Type: "Business Classification",
  Order_Nbbo_Source: "Economics",
  Order_Nbbo_Timestamp: "Economics",
  Order_Solicitation_Flag: "Business Classification",
  Order_Net_Price: "Economics",
  Route_Rejected_Flag: "Business Classification",
  Order_Origination_System: "Identifier",
  Order_Placeholder_1: "Economics",
  Order_Placeholder_2: "Economics",
  Order_Placeholder_3: "Economics",
  Order_Placeholder_4: "Economics",
  Order_Placeholder_5: "Economics",
};

const executionFields = {
  Execution_Identifier: "Identifier",
  Previous_Execution_ID: "Identifier",
  Execution_Entity_ID: "Identifier",
  Execution_Version: "Identifier",
  Execution_Seq_Number: "Identifier",
  External_Execution_ID: "Identifier",
  Execution_Side: "Economics",
  Execution_Posting_Side: "Economics",
  Execution_Allocation_Side: "Economics",
  Execution_Broker_Capacity: "Business Classification",
  Execution_Capacity: "Business Classification",
  Execution_Event_Time: "Economics",
  Execution_Time: "Economics",
  Execution_Manual_Indicator: "Business Classification",
  Execution_Manual_Event_Time: "Economics",
  Is_Market_Execution: "Business Classification",
  Execution_Last_Market: "Economics",
  Execution_Account: "Identifier",
  Execution_Booking_Account: "Identifier",
  Execution_Booking_Entity: "Business Classification",
  Execution_Trading_Entity: "Business Classification",
  Execution_Desk_ID: "Identifier",
  Execution_OSI: "Economics",
  Execution_Instrument_ID: "Identifier",
  Execution_Linked_Instrument_ID: "Identifier",
  Execution_Symbol: "Economics",
  Execution_Instrument_Reference: "Identifier",
  Execution_Instrument_Reference_Value: "Identifier",
  Execution_Last_Price: "Economics",
  Execution_Last_Quantity: "Economics",
  Execution_Contra_Broker: "Business Classification",
  Linked_Execution_ID: "Identifier",
  Execution_Transaction_Type: "Business Classification",
  Execution_ID_Instance: "Identifier",
  Execution_Session: "Identifier",
  Execution_Order_ID_Instance: "Identifier",
  Execution_Order_ID_Session: "Identifier",
  executon_Order_ID: "Identifier",
  Execution_Order_ID_Version: "Identifier",
  Execution_Trade_Execution_System: "Economics",
  Execution_OMS_Source: "Identifier",
  Execution_Booking_Eligiblity: "Business Classification",
  Execution_Trade_Date: "Economics",
  Execution_Currency_ID: "Identifier",
  Execution_Position_ID: "Identifier",
  Execution_Swap_Indicator: "Business Classification",
  Execution_Settle_Date: "Economics",
  Execution_Commision_Fee: "Economics",
  Execution_Rollup_ID: "Identifier",
  Execution_Secondary_Offering: "Business Classification",
  Execution_Cum_Quantity: "Economics",
  Execution_Trade_Factors: "Economics",
  Execution_Risk_Date: "Economics",
  Execution_Order_Compliance_ID: "Identifier",
  Execution_InfoBarrier_ID: "Business Classification",
  Executon_Session_Actual: "Business Classification",
  Execution_Strategy: "Business Classification",
  Execution_Last_Liquidity_Indicator: "Economics",
  Execution_Waiver_Indicator: "Business Classification",
  Execution_Lifecycle_Type: "Business Classification",
  Execution_Package_Indicator: "Economics",
  Execution_Raw_Liquidity_Indicator: "Economics",
  Execution_Package_ID: "Business Classification",
  Execution_Quote_ID: "Identifier",
  Execution_Yield: "Economics",
  Execution_Spread: "Economics",
  Execution_Negotiated_Indicator: "Business Classification",
  Execution_Open_Close_Indicator: "Economics",
  Exchange_Exec_ID: "Economics",
  Execution_Action: "Business Classification",
  Execution_Cross_ID: "Identifier",
  Execution_Executing_Entity: "Business Classification",
  Regulatory_Execution_ID: "Economics",
  Regulatory_Execution_Venue: "Business Classification",
  Execution_Placeholder_2: "Economics",
  Execution_Placeholder_3: "Economics",
  Execution_Placeholder_4: "Economics",
  Execution_Placeholder_5: "Economics",
};

module.exports = {
  orderFields,
  executionFields,
};
