// Auto-generated from "Order & Execution Object Mapping, Business Criteria & Business Classification.xlsx" on 2025-12-25T13:54:51.857Z
// Column B = Field Name, Column F = Field Type (mapped to Identifier/Business Classification/Economics)

const orderFields = {
  "Order_ID": "Identifier",
  "Order_ID_Version": "Identifier",
  "Order_ID_Session": "Identifier",
  "Order_ID_Instance": "Identifier",
  "Parent_Order_ID": "Identifier",
  "Cancelreplace_Order_ID": "Identifier",
  "Linked_Order_ID": "Identifier",
  "Linked_Order_Type": "Business Classification",
  "Order_Action": "Business Classification",
  "Order_Status": "Business Classification",
  "Order_Capacity": "Business Classification",
  "Order_Destination": "Economics",
  "Order_Client_Ref": "Business Classification",
  "Order_Client_Ref_Details": "Business Classification",
  "Order_Executing_Entity": "Business Classification",
  "Order_Booking_Entity": "Business Classification",
  "Order_Position_Account": "Identifier",
  "Order_Side": "Economics",
  "Order_Client_Capacity": "Business Classification",
  "Order_Manual_Indicator": "Business Classification",
  "Order_Request_Time": "Economics",
  "Order_Event_Time": "Economics",
  "Order_Manual_Timestamp": "Economics",
  "Order_OMS_Source": "Identifier",
  "Order_Publishing_Time": "Economics",
  "Order_Trade_Date": "Economics",
  "Order_Quantity": "Economics",
  "Order_Price": "Economics",
  "Order_Type": "Economics",
  "Order_TimeInforce": "Economics",
  "Order_Execution_Instructions": "Economics",
  "Order_Attributes": "Economics",
  "Order_Restrictions": "Business Classification",
  "Order_Auction_Indicator": "Economics",
  "Order_Swap_Indicator": "Business Classification",
  "Order_OSI": "Economics",
  "Order_Instrument_ID": "Identifier",
  "Order_Linked_Instrument_ID": "Identifier",
  "Order_Currency_ID": "Identifier",
  "Order_Flow_Type": "Business Classification",
  "Order_Algo_Instruction": "Economics",
  "Order_Symbol": "Economics",
  "Order_Instrument_Reference": "Identifier",
  "Order_Instrument_Reference_Value": "Identifier",
  "Order_Option_Put_Call": "Economics",
  "Order_Option_Strike_Price": "Economics",
  "Order_Option_Leg_Indicator": "Economics",
  "Order_Compliance_ID": "Identifier",
  "Order_Entity_ID": "Identifier",
  "Order_Executing_Account": "Identifier",
  "Order_Clearing_Account": "Identifier",
  "Order_Client_Order_ID": "Identifier",
  "Order_Routed_Order_ID": "Economics",
  "Order_Trading_Owner": "Business Classification",
  "Order_Extended_Attribute": "Business Classification",
  "Order_Quote_ID": "Identifier",
  "Order_Represent_Order_ID": "Identifier",
  "Order_On_Behalf_Comp_ID": "Identifier",
  "Order_Spread": "Economics",
  "Order_Amend_Reason": "Business Classification",
  "Order_Cancel_Reject_Reason": "Business Classification",
  "Order_Bid_Size": "Economics",
  "Order_Bid_Price": "Economics",
  "Order_Ask_Size": "Economics",
  "Order_Ask_Price": "Economics",
  "Order_Basket_ID": "Identifier",
  "Order_Cum_Qty": "Economics",
  "Order_Leaves_Qty": "Economics",
  "Order_Stop_Price": "Economics",
  "Order_Discretion_Price": "Economics",
  "Order_Exdestination_Instruction": "Economics",
  "Order_Execution_Parameter": "Economics",
  "Order_Infobarrier_ID": "Business Classification",
  "Order_Leg_Ratio": "Economics",
  "Order_Locate_ID": "Business Classification",
  "Order_Negotiated_Indicator": "Business Classification",
  "Order_Open_Close": "Business Classification",
  "Order_Participant_Priority_Code": "Business Classification",
  "Order_Action_Initiated": "Business Classification",
  "Order_Package_Indicator": "Business Classification",
  "Order_Package_ID": "Business Classification",
  "Order_Package_Pricetype": "Business Classification",
  "Order_Strategy_Type": "Business Classification",
  "Order_Secondary_Offering": "Business Classification",
  "Order_Start_Time": "Business Classification",
  "Order_TIF_Expiration": "Business Classification",
  "Order_Parent_Child_type": "Business Classification",
  "Order_Minimum_Qty": "Business Classification",
  "Order_Trading_Session": "Business Classification",
  "Order_Display_Price": "Business Classification",
  "Order_Seq_Number": "Business Classification",
  "ATS_Display_Indicator": "Business Classification",
  "Order_Display_Qty": "Business Classification",
  "Order_Working_Price": "Business Classification",
  "ATS_Order_Type": "Business Classification",
  "Order_Nbbo_Source": "Business Classification",
  "Order_Nbbo_Timestamp": "Business Classification",
  "Order_Solicitation_Flag": "Business Classification",
  "Order_Net_Price": "Business Classification",
  "Route_Rejected_Flag": "Business Classification",
  "Order_Origination_System": "Business Classification",
  "Order_Placeholder_1": "—",
  "Order_Placeholder_2": "—",
  "Order_Placeholder_3": "—",
  "Order_Placeholder_4": "—",
  "Order_Placeholder_5": "—"
};

const executionFields = {
  "Previous_Execution_ID": "Identifier",
  "Execution_Entity_ID": "Identifier",
  "Execution_Version": "Identifier",
  "Execution_Seq_Number": "Identifier",
  "External_Execution_ID": "Identifier",
  "Execution_Side": "Business Classification",
  "Execution_Posting_Side": "Business Classification",
  "Execution_Allocation_Side": "Business Classification",
  "Execution_Broker_Capacity": "Business Classification",
  "Execution_Capacity": "Business Classification",
  "Execution_Event_Time": "Business Classification",
  "Execution_Time": "Business Classification",
  "Execution_Manual_Indicator": "Business Classification",
  "Execution_Manual_Event_Time": "Business Classification",
  "Is_Market_Execution": "Business Classification",
  "Execution_Last_Market": "Business Classification",
  "Execution_Account": "Business Classification",
  "Execution_Booking_Account": "Business Classification",
  "Execution_Booking_Entity": "Business Classification",
  "Execution_Trading_Entity": "Business Classification",
  "Execution_Desk_ID": "Business Classification",
  "Execution_OSI": "Business Classification",
  "Execution_Instrument_ID": "Business Classification",
  "Execution_Linked_Instrument_ID": "Business Classification",
  "Execution_Symbol": "Business Classification",
  "Execution_Instrument_Reference": "Business Classification",
  "Execution_Instrument_Reference_Value": "Business Classification",
  "Execution_Last_Price": "Business Classification",
  "Execution_Last_Quantity": "Business Classification",
  "Execution_Contra_Broker": "Business Classification",
  "Linked_Execution_ID": "Identifier",
  "Execution_Transaction_Type": "Business Classification",
  "Execution_ID_Instance": "Identifier",
  "Execution_Session": "Identifier",
  "Execution_Order_ID_Instance": "Identifier",
  "Execution_Order_ID_Session": "Identifier",
  "Executon_Order_ID": "Identifier",
  "Execution_Order_ID_Version": "Identifier",
  "Execution_Trade_Execution_System": "Business Classification",
  "Execution_OMS_Source": "Business Classification",
  "Execution_Booking_Eligiblity": "Business Classification",
  "Execution_Trade_Date": "Business Classification",
  "Execution_Currency_ID": "Business Classification",
  "Execution_Position_ID": "Business Classification",
  "Execution_Swap_Indicator": "Business Classification",
  "Execution_Settle_Date": "Business Classification",
  "Execution_Commision_Fee": "Business Classification",
  "Execution_Rollup_ID": "Business Classification",
  "Execution_Secondary_Offering": "Business Classification",
  "Execution_Cum_Quantity": "Business Classification",
  "Execution_Trade_Factors": "Business Classification",
  "Execution_Risk_Date": "Business Classification",
  "Execution_Order_Compliance_ID": "Identifier",
  "Execution_InfoBarrier_ID": "Business Classification",
  "Executon_Session_Actual": "Business Classification",
  "Execution_Strategy": "Business Classification",
  "Execution_Last_Liquidity_Indicator": "Business Classification",
  "Execution_Waiver_Indicator": "Business Classification",
  "Execution_Lifecycle_Type": "Business Classification",
  "Execution_Package_Indicator": "Business Classification",
  "Execution_Raw_Liquidity_Indicator": "Business Classification",
  "Execution_Package_ID": "Business Classification",
  "Execution_Quote_ID": "Business Classification",
  "Execution_Yield": "Business Classification",
  "Execution_Spread": "Business Classification",
  "Execution_Negotiated_Indicator": "Business Classification",
  "Execution_Open_Close_Indicator": "Business Classification",
  "Exchange_Exec_ID": "Business Classification",
  "Execution_Action": "Business Classification",
  "Execution_Cross_ID": "Business Classification",
  "Execution_Executing_Entity": "Business Classification",
  "Regulatory_Execution_ID": "—",
  "Execution_Placeholder_1": "—",
  "Execution_Placeholder_2": "—",
  "Execution_Placeholder_3": "—",
  "Execution_Placeholder_4": "—",
  "Execution_Placeholder_5": "—"
};

module.exports = {
  orderFields,
  executionFields,
};
